---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicename
  name: service-name-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicename
  template:
    metadata:
      labels:
        app: servicename
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: registry-docker-hub
      containers:
        - image: imageregistry/servicename:v1
          name: servicename
          ports:
            - name: http
              containerPort: 8700
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 100m
              memory: 300Mi
          securityContext:
            runAsNonRoot: true
