---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicename
  name: service-name-deploy
  namespace: servicename
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicename
  template:
    metadata:
      labels:
        app: servicename
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: registry-docker-hub
      containers:
        - image: mayur21486/helloapp:ee2c972a4054ef6968edb59ecbd4eb6f3c077dc6
          name: servicename
          ports:
            - name: http
              containerPort: 8700
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 200m
              memory: 500Mi
          # securityContext:
          #   runAsNonRoot: true
