apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

#components:
#- ../../../remote/kustomize-bases/components/security

images:
- name: opengovorg/template-service-java
  newTag: sha-f4c6ec3
