---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicename
  name: servicename-service
  namespace: servicename
spec:
  type: NodePort  # Allows external access
  ports:
    - name: http
      port: 80
      targetPort: 8700
      nodePort: 30001 # Access via http://<Any_Node_IP>:30001
  selector:
    app: servicename
