---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicename
  name: servicename-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8700
  selector:
    app: servicename
